export const API_URL = "http://localhost:8080";

export const thunkUserTypes = {
  GET_USER: "GET_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",
  GET_ADDRESS_USER: "GET_ADDRESS_USER",
  GET_BILL_BY_USER: "GET_BILL_BY_USER",
};

export const thunkProductTypes = {
  GETALL_PRODUCT: "GETALL_PRODUCT",
  GET_PRODUCT: "GET_PRODUCT",
  GET_PRODUCT_BY_CATEGORY: "GET_PRODUCT_BY_CATEGORY",
  GET_PRODUCT_BY_BRAND: "GET_PRODUCT_BY_BRAND",
  GET_PRODUCT_BY_DISCOUNT: "GET_PRODUCT_BY_DISCOUNT",
  GET_PRODUCT_FEEDBACK: "GET_PRODUCT_FEEDBACK"
};

export const thunkCategoryTypes = {
  GETALL_CATEGORY: "GETALL_CATEGORY",
  GET_CATEGORY: "GET_CATEGORY",
};

export const thunkBrandTypes = {
  GETALL_BRAND: "GETALL_BRAND",
  GET_BRAND: "GET_BRAND",
};

export const thunkCartTypes = {
  GET_CART_USER: "GET_CART_USER",
  GET_DETAIL_CART_USER: "GET_DETAIL_CART_USER",
};