export const API_URL = "http://localhost:8080";

export const thunkUserTypes = {
  GETALL_USER: "GETALL_USER",
  GET_USER: "GET_USER",
};

export const thunkProductTypes = {
  GETALL_PRODUCT: "GETALL_PRODUCT",
  GET_PRODUCT: "GET_PRODUCT",
  GET_PRODUCT_SALE: "GET_PRODUCT_SALE",
};

export const thunkCategoryTypes = {
  GETALL_CATEGORY: "GETALL_CATEGORY",
  GET_CATEGORY: "GET_CATEGORY",
};

export const thunkBrandTypes = {
  GETALL_BRAND: "GETALL_BRAND",
  GET_BRAND: "GET_BRAND",
};

export const thunkRoleTypes = {
  GETALL_ROLE: "GETALL_ROLE",
  GET_ROLE: "GET_ROLE",
};

export const thunkFeedbackTypes = {
  GETALL_FEEDBACK: "GETALL_FEEDBACK",
  GET_FEEDBACK: "GET_FEEDBACK",
};

export const thunkDiscountTypes = {
  GETALL_DISCOUNT: "GETALL_DISCOUNT",
  GET_DISCOUNT: "GET_DISCOUNT",
};

export const thunkBillTypes = {
  GETALL_BILL_WAITING: "GETALL_BILL_WAITING",
  GETALL_BILL_CHECKED: "GETALL_BILL_CHECKED",
  GETALL_BILL_DELIVERING: "GETALL_BILL_DELIVERING",
  GETALL_BILL_DELIVERED: "GETALL_BILL_DELIVERED",
  GETALL_BILL_CANCEL: "GETALL_BILL_CANCEL"
};

export const thunkStatisticTypes = {
  STATISTIC_USER: 'STATISTIC_USER',
  STATISTIC_FIVE_USER: 'STATISTIC_FIVE_USER',
  STATISTIC_FIVE_TRANSACTION: 'STATISTIC_FIVE_TRANSACTION',
  STATISTIC_PRODUCT: 'STATISTIC_PRODUCT',
  STATISTIC_BILL: 'STATISTIC_BILL',
  STATISTIC_SALE: 'STATISTIC_SALE',
  STATISTIC_REVENUE: 'STATISTIC_REVENUE',
  STATISTIC_TRANSACTION: 'STATISTIC_TRANSACTION',
  STATISTIC_TIME_USER: 'STATISTIC_TIME_USER',
  STATISTIC_SALE_PRODUCT: 'STATISTIC_SALE_PRODUCT',
  STATISTIC_SALE_DATE: 'STATISTIC_SALE_DATE',
};